### ISSUE TITLE
Cant load the data SP100.RData nor Russell3000.RData with R 3.5 nor R 4.1.2 

### ISSUE THREAD

**Issue by BrunoSpilak** [QuantLet/RobustM#1]
Which version of R did you use the save the data ?

**Comment by BrunoSpilak** [comment]
> load("Russell3000.RData")
Error in base::load(..., envir = envir) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘Russell3000.RData’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated

**Comment by allapetukhina** [comment]
1. RData and csv files are traced by LFS: https://github.com/QuantLet/RobustM/blob/main/.gitattributes
2. Please check session info for packages/R version used 
 https://github.com/QuantLet/RobustM/blob/main/RobustM_PerformanceRussell3000/sessionInfo.txt
